In [1]:
print('하하하')

하하하


In [10]:
import numpy as np
from numpy import genfromtxt

np.random.rand(3, 4) # 3x4행렬에 난수 생성

array([[0.0184251 , 0.68998681, 0.85887289, 0.49251629],
       [0.23326818, 0.79145646, 0.79625743, 0.39042176],
       [0.86901202, 0.76433357, 0.01669926, 0.98294015]])

In [3]:
list = [3, 4.1 , 5, 6.3, 7, 8.6] # 단일 리스트
arr = np.array(list)

print('평균', arr.mean()) # 기술통계
print('합계', arr.sum())
print('최대값', arr.max())
print('최소값', arr.min())
print('분산', arr.var())
print('표준편차', arr.std())

평균 5.666666666666667
합계 34.0
최대값 8.6
최소값 3.0
분산 3.465555555555555
표준편차 1.8616002673924268


In [5]:
list = [ [9, 8, 7, 6, 5], [1, 2, 3, 4, 5] ] # 중첩리스트
arr = np.array(list)
print(arr)
print(arr[0, 2]) # 7
print(arr[1, 4]) # 4
print(arr[0, :]) # 9 8 7 6 5 행 전체 출력
print(arr[:, 1]) # 8 2       열 전체 출력

[[9 8 7 6 5]
 [1 2 3 4 5]]
7
5
[9 8 7 6 5]
[8 2]


In [6]:
# 자동으로 채워지는 행렬 생성
zarr = np.zeros( (3, 5) ) # 0으로 채워지는 3x5 행렬 생성

# 정수 생성
cnt = 0
for i in np.arange(3):
    for j in np.arange(5):
        cnt += 1
        zarr[i, j] = cnt

print(zarr)


[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


In [8]:
# 외부 csv 파일 읽어서 배열 생성
phone = genfromtxt('D:/빅데이터/data/pdf/빅데이터/데이터분석통계/data/phone-01.csv', delimiter = ',')
print(phone)
print( np.mean( phone[:, 2] ) ) # 화면크기 항목에 대한 평균 출력
print( np.median( phone[:, 2] ) ) # 화면크기 항목에 대한 평균 출력

print('총 갯수 :', len(phone))

p_col3 = phone[:, 2]
print(np.percentile(p_col3, 0)) # 사분위값 : 최소값
print(np.percentile(p_col3, 25)) # 1사분위값
print(np.percentile(p_col3, 50)) # 2사분위값
print(np.percentile(p_col3, 75)) # 3사분위값
print(np.percentile(p_col3, 100)) # 사분위값 : 최대값

# scipy에는 여러가지 기술통계를 한번에 계산해주는
# describe 함수가 있음
from scipy.stats import describe
print( describe(p_col3) )

[[2015.  2015.     5. ]
 [2014.  2015.     4.5]
 [2015.  2015.     5. ]
 [2015.  2016.     5. ]
 [2015.  2015.     5. ]
 [2016.  2016.     5.5]
 [2016.  2016.     6. ]
 [2014.  2014.     5. ]
 [2014.  2014.     4.5]
 [2015.  2014.     5. ]
 [2014.  2015.     4.5]
 [2015.  2015.     5.5]
 [2015.  2016.     5.5]
 [2015.  2015.     6. ]
 [2015.  2015.     5.5]
 [2015.  2015.     5. ]
 [2016.  2016.     5.5]
 [2016.  2016.     6. ]
 [2015.  2015.     4.5]
 [2016.  2016.     5.5]
 [2015.  2015.     5.5]
 [2016.  2016.     5.5]
 [2015.  2015.     5. ]
 [2016.  2016.     6. ]]
5.25
5.25
총 갯수 : 24
4.5
5.0
5.25
5.5
6.0


DescribeResult(nobs=24, minmax=(4.5, 6.0), mean=5.25, variance=0.2391304347826087, skewness=0.0, kurtosis=-0.942148760330578)
